# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b6e148bdc1c3c102b6864b2e78a0ddc308c299b2f0f3321f239b1ac63940b21c3b283b0f4e2f0771dffe9a0310770a75d7afc9b7890d7137d0becf9091a323

test:
  secret_key_base: c66d67fd4b3118e5d42124e099a48a305eaeccd43a67fe10db26fab15cd7691f115fd6c8ed0fc30eb89bedab9c296bda3f7c288b6aad0810eb2e4dfa32b37543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
